# Generated by Django 4.0.2 on 2022-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='article name', max_length=200)),
                ('amount', models.IntegerField(help_text='number of items')),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('storage_time', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
    ]
