# Generated by Django 4.0.2 on 2022-03-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_product_storage_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-delivery_date'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
