# Generated by Django 4.0.2 on 2022-03-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(choices=[('BYN', 'Rubles'), ('USD', 'Dollars'), ('EUR', 'Euro')], decimal_places=2, default='BYN', max_digits=8, max_length=3),
        ),
    ]
